version: '3'

services:
  app:
    build:
      context: ./src/
      dockerfile: Dockerfile
      args:
      - NODE_ENV=development
    ports:
      - "4001:4000"
    # volumes:
    #   - ./src:/app
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL=http://localhost:4001
