version: '3'

services:
  app:
    build: ./src
    container_name: my_app_container
    ports:
      - "4000:4000"
    depends_on:
      - mysql
    restart: unless-stopped
    # volumes:
    #   - ./src:/app

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx_proxy
  #   restart: unless-stopped
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - app

  mysql:
    image: mysql:8
    container_name: my_mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: unless-stopped

  # adminer:
    # image: phpmyadmin
    # container_name: my_phpmyadmin_container
    # environment:
    #   PMA_HOST: mysql
    #   PMA_PORT: 3306
    # ports:
    #   - "8080:80"
    # depends_on:
    #   - mysql
    # restart: unless-stopped
